# Generated by Django 4.0.5 on 2022-06-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_package',
        ),
        migrations.AddField(
            model_name='package',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waybill.shipment'),
            preserve_default=False,
        ),
    ]
