# Generated by Django 4.0.5 on 2022-06-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
        ('waybill', '0002_remove_shipment_shipment_package_package_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='carrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waybill.receiver'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waybill.sender'),
        ),
    ]
