# Generated by Django 4.0.5 on 2022-06-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_carrierfunction_carrier_carrier_functions'),
        ('waybill', '0004_alter_package_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybill.receiver'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybill.sender'),
        ),
    ]
