# Generated by Django 4.0.5 on 2022-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0005_alter_waybill_carrier_alter_waybill_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
