# Generated by Django 4.0.5 on 2022-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0006_alter_receiver_email_alter_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='way_bill_number',
            field=models.UUIDField(unique=True),
        ),
    ]
