# Generated by Django 4.0.5 on 2022-06-12 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0007_alter_shipment_shipment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='way_bill_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
