# Generated by Django 4.0.5 on 2022-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carrier Functions',
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='carrier_functions',
            field=models.ManyToManyField(blank=True, to='carrier.carrierfunction'),
        ),
    ]
