# Generated by Django 4.0.5 on 2022-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_carrierfunction_carrier_carrier_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
